### ISSUE TITLE
Migrate to MavenCentral

### ISSUE THREAD

**Issue by marcelpinto** [marcelpinto/permissions-ktx#11]
Ditch JCenter!

**Comment by erikeelde** [comment]
want help with this? would be lovely to have that artifact available. :)

**Comment by marcelpinto** [comment]
Oh absolutely. I want to find time on the weekend to check the migration guides but if you want to kick it off go ahead!

**Comment by inktomi** [comment]
Hopefully this migration will go smoothly for you. Happy to help as I can, though I'm sure you'll want your own keys and such.

**Comment by warting** [comment]
I'm waiting for this one. Only thing left before I can remove JCenter repo from my app.

**Comment by marcelpinto** [comment]
I'm struggling to find time, I hope I can take a look soon.

**Comment by marcelpinto** [comment]
Okay I found time :)

JCenter can be drop and you should be able to get it from MavenCentral:

```
implementation("dev.marcelpinto:permissions-ktx:0.9")
// or
implementation("dev.marcelpinto:permissions-compose-ktx:0.9")
```

**Comment by warting** [comment]
Awesome, thanks!

**Comment by inktomi** [comment]
Thank you!!
